namespace ArduinoExpressConfig {
  const int MAX_ROUTECALLBACKS_COUNT = 7;
  const int MAX_MIDDLEWARECALLBACKS_COUNT = 1;
  const int MAX_ROUTERS_COUNT = 3;
  const int MAX_CALLBACKS_COUNT = MAX_ROUTECALLBACKS_COUNT + MAX_MIDDLEWARECALLBACKS_COUNT + MAX_ROUTERS_COUNT;


  const int MAX_PARAMS_COUNT = 1;
  const int MAX_HEADERS_COUNT = 12;
}
